### ISSUE TITLE
III stage

### ISSUE THREAD

**Issue by rusdevops** [IlyaHoloday/VkClient#1]
@IlyaHoloday 

- [ ] 1. Отсутствует проверка корректного состояния стандартного потока ввода.
 [здесь](https://github.com/IlyaHoloday/VkClient/blob/12f6b22483e2c69bbddedd125d095f56f97c7f5c/examples/main.cpp#L15), [здесь](https://github.com/IlyaHoloday/VkClient/blob/12f6b22483e2c69bbddedd125d095f56f97c7f5c/source/client.cpp#L114) и [здесь](https://github.com/IlyaHoloday/VkClient/blob/12f6b22483e2c69bbddedd125d095f56f97c7f5c/source/client.cpp#L117).
- [ ] 2. Отсутствует оптимизация. [здесь](https://github.com/IlyaHoloday/VkClient/blob/12f6b22483e2c69bbddedd125d095f56f97c7f5c/examples/main.cpp#L19-L20) и [здесь](https://github.com/IlyaHoloday/VkClient/blob/12f6b22483e2c69bbddedd125d095f56f97c7f5c/source/client.cpp#L121).
- [x] 3. Не корректное именование переменных. [здесь](https://github.com/IlyaHoloday/VkClient/blob/12f6b22483e2c69bbddedd125d095f56f97c7f5c/examples/main.cpp#L17), [здесь](https://github.com/IlyaHoloday/VkClient/blob/12f6b22483e2c69bbddedd125d095f56f97c7f5c/examples/main.cpp#L19) и [здесь](https://github.com/IlyaHoloday/VkClient/blob/12f6b22483e2c69bbddedd125d095f56f97c7f5c/source/client.cpp#L112).
- [ ] 4. Отсутствует проверка корректного состояния потока. [здесь](https://github.com/IlyaHoloday/VkClient/blob/12f6b22483e2c69bbddedd125d095f56f97c7f5c/source/client.cpp#L125).
- [ ] 5. Отсутствует обработка возвращаемого значения. [здесь](https://github.com/IlyaHoloday/VkClient/blob/12f6b22483e2c69bbddedd125d095f56f97c7f5c/examples/main.cpp#L21).
- [x] 6. Присутствуют избыточные комментарии. [здесь](https://github.com/IlyaHoloday/VkClient/blob/12f6b22483e2c69bbddedd125d095f56f97c7f5c/source/client.cpp#L22), [здесь](https://github.com/IlyaHoloday/VkClient/blob/12f6b22483e2c69bbddedd125d095f56f97c7f5c/source/client.cpp#L31) и [здесь](https://github.com/IlyaHoloday/VkClient/blob/12f6b22483e2c69bbddedd125d095f56f97c7f5c/include/vk/Friend.hpp#L20).
- [x] 7. Присутствует дублирование кода. [здесь](https://github.com/IlyaHoloday/VkClient/blob/12f6b22483e2c69bbddedd125d095f56f97c7f5c/source/client.cpp#L28-L33).
- [x] 8. Присутствует избыточный код. [здесь](https://github.com/IlyaHoloday/VkClient/blob/12f6b22483e2c69bbddedd125d095f56f97c7f5c/source/client.cpp#L23) и [здесь](https://github.com/IlyaHoloday/VkClient/blob/12f6b22483e2c69bbddedd125d095f56f97c7f5c/source/client.cpp#L32).

**Comment by IlyaHoloday** [comment]
Исправил, только сейчас закончил. Отталкивался от сданных работ, чтобы исправить ошибки.
